// Generated by scripts/generate-native-tools.ts from src/features/agent-runtime/toolDocs.ts.
// Do not edit by hand.
export const nativeTools = [
  {
    name: 'runtime_execute_code',
    short: 'Runtime Execute Code',
    desc: 'Run short JavaScript against direct bridge namespaces for Discord, history, context, admin, moderation, scheduling, HTTP, and workspace access.',
    cat: 'system',
    color: '#6B7280',
  },
];

export const nativeToolCount = nativeTools.length;
