// Generated by scripts/generate-native-tools.ts from src/features/agent-runtime/toolDocs.ts.
// Do not edit by hand.
export const nativeTools = [
  {
    "name": "discord_admin_add_member_role",
    "short": "Discord Admin Add Member Role",
    "desc": "Add an existing guild role to a member with admin approval.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_api",
    "short": "Discord Admin Api",
    "desc": "Guild-scoped raw Discord API fallback.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_archive_thread",
    "short": "Discord Admin Archive Thread",
    "desc": "Archive a thread explicitly.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_clear_governance_review_channel",
    "short": "Discord Admin Clear Governance Review Channel",
    "desc": "Clear the dedicated governance review channel.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_clear_server_api_key",
    "short": "Discord Admin Clear Server Api Key",
    "desc": "Clear the current server-wide API key.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_create_channel",
    "short": "Discord Admin Create Channel",
    "desc": "Create a new channel or category.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_create_forum_post",
    "short": "Discord Admin Create Forum Post",
    "desc": "Create a forum post in a forum channel.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_create_invite",
    "short": "Discord Admin Create Invite",
    "desc": "Create a new invite for a channel.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_create_role",
    "short": "Discord Admin Create Role",
    "desc": "Create a new guild role with Discord admin approval and server context.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_create_scheduled_event",
    "short": "Discord Admin Create Scheduled Event",
    "desc": "Create a scheduled event for the guild.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_delete_message",
    "short": "Discord Admin Delete Message",
    "desc": "Delete a message with admin approval.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_delete_role",
    "short": "Discord Admin Delete Role",
    "desc": "Delete an existing guild role with admin approval and guild context.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_delete_scheduled_event",
    "short": "Discord Admin Delete Scheduled Event",
    "desc": "Delete a scheduled event for the guild.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_edit_channel",
    "short": "Discord Admin Edit Channel",
    "desc": "Edit an existing channel.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_edit_message",
    "short": "Discord Admin Edit Message",
    "desc": "Edit a message with admin approval.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_edit_role",
    "short": "Discord Admin Edit Role",
    "desc": "Edit an existing guild role, including name, color, or permissions, with approval.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_get_governance_review_status",
    "short": "Discord Admin Get Governance Review Status",
    "desc": "Inspect where governance review cards are routed.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_get_invite_url",
    "short": "Discord Admin Get Invite Url",
    "desc": "Generate an OAuth2 invite URL for the bot.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_get_server_key_status",
    "short": "Discord Admin Get Server Key Status",
    "desc": "Check the current server-wide API key status.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_list_invites",
    "short": "Discord Admin List Invites",
    "desc": "List active guild or channel invites.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_pin_message",
    "short": "Discord Admin Pin Message",
    "desc": "Pin a message with admin approval.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_remove_member_role",
    "short": "Discord Admin Remove Member Role",
    "desc": "Remove a role from a member.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_reopen_thread",
    "short": "Discord Admin Reopen Thread",
    "desc": "Reopen an archived thread explicitly.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_revoke_invite",
    "short": "Discord Admin Revoke Invite",
    "desc": "Revoke an invite by its code.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_send_key_setup_card",
    "short": "Discord Admin Send Key Setup Card",
    "desc": "Send an interactive server-key setup card.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_set_governance_review_channel",
    "short": "Discord Admin Set Governance Review Channel",
    "desc": "Route governance review cards to a specific text channel.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_submit_moderation",
    "short": "Discord Admin Submit Moderation",
    "desc": "Submit a moderation or enforcement request.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_unpin_message",
    "short": "Discord Admin Unpin Message",
    "desc": "Unpin a message with admin approval.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_update_forum_tags",
    "short": "Discord Admin Update Forum Tags",
    "desc": "Replace the applied tags on a forum thread.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_update_scheduled_event",
    "short": "Discord Admin Update Scheduled Event",
    "desc": "Update a scheduled event for the guild.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_admin_update_server_instructions",
    "short": "Discord Admin Update Server Instructions",
    "desc": "Submit an admin request to update the guild Sage Persona.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_context_get_channel_summary",
    "short": "Discord Context Get Channel Summary",
    "desc": "Fetch rolling and long-term summary context for the current channel.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_context_get_server_instructions",
    "short": "Discord Context Get Server Instructions",
    "desc": "Read the current guild Sage Persona instructions.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_context_get_social_graph",
    "short": "Discord Context Get Social Graph",
    "desc": "Retrieve social graph relationships for a user.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_context_get_top_relationships",
    "short": "Discord Context Get Top Relationships",
    "desc": "Show the top interaction pairs in this server.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_context_get_user_profile",
    "short": "Discord Context Get User Profile",
    "desc": "Fetch the best-effort personalization profile for a user.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_context_get_voice_analytics",
    "short": "Discord Context Get Voice Analytics",
    "desc": "Retrieve voice participation analytics.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_context_get_voice_summaries",
    "short": "Discord Context Get Voice Summaries",
    "desc": "Retrieve recent voice session summaries.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_context_search_channel_summary_archives",
    "short": "Discord Context Search Channel Summary Archives",
    "desc": "Search archived summary context for the current channel.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_files_find_channel",
    "short": "Discord Files Find Channel",
    "desc": "Search attachment text in the current channel.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_files_find_server",
    "short": "Discord Files Find Server",
    "desc": "Search attachment text across the guild.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_files_list_channel",
    "short": "Discord Files List Channel",
    "desc": "List cached attachments in the current channel.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_files_list_server",
    "short": "Discord Files List Server",
    "desc": "List cached attachments across the guild.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_files_read_attachment",
    "short": "Discord Files Read Attachment",
    "desc": "Read cached attachment text in pages.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_files_send_attachment",
    "short": "Discord Files Send Attachment",
    "desc": "Resend a cached attachment as a distinct artifact.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_messages_add_reaction",
    "short": "Discord Messages Add Reaction",
    "desc": "Add a reaction to a Discord message.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_messages_create_poll",
    "short": "Discord Messages Create Poll",
    "desc": "Create a poll in Discord.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_messages_get_context",
    "short": "Discord Messages Get Context",
    "desc": "Retrieve messages before and after a given message ID.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_messages_get_user_timeline",
    "short": "Discord Messages Get User Timeline",
    "desc": "Show recent messages from a user across the guild.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_messages_remove_self_reaction",
    "short": "Discord Messages Remove Self Reaction",
    "desc": "Remove Sage’s own reaction from a Discord message.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_messages_search_guild",
    "short": "Discord Messages Search Guild",
    "desc": "Search raw message history across the guild.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_messages_search_history",
    "short": "Discord Messages Search History",
    "desc": "Search channel message history.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_messages_search_with_context",
    "short": "Discord Messages Search With Context",
    "desc": "Search channel history and expand context around the best match.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_add_thread_member",
    "short": "Discord Server Add Thread Member",
    "desc": "Add a member to a thread.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_create_thread",
    "short": "Discord Server Create Thread",
    "desc": "Create a Discord thread.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_get_channel",
    "short": "Discord Server Get Channel",
    "desc": "Retrieve detailed metadata for one guild channel.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_get_member",
    "short": "Discord Server Get Member",
    "desc": "Retrieve one guild member.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_get_permission_snapshot",
    "short": "Discord Server Get Permission Snapshot",
    "desc": "Resolve permissions for a user or role in a specific channel.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_get_scheduled_event",
    "short": "Discord Server Get Scheduled Event",
    "desc": "Retrieve one scheduled event for the active guild.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_get_thread",
    "short": "Discord Server Get Thread",
    "desc": "Retrieve detailed metadata for one thread.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_join_thread",
    "short": "Discord Server Join Thread",
    "desc": "Join an existing Discord thread as Sage so later thread-scoped actions can proceed.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_leave_thread",
    "short": "Discord Server Leave Thread",
    "desc": "Leave an existing Discord thread as Sage after thread-scoped work is complete.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_list_automod_rules",
    "short": "Discord Server List Automod Rules",
    "desc": "List AutoMod rules for the active guild.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_list_channels",
    "short": "Discord Server List Channels",
    "desc": "List accessible guild channels and categories.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_list_members",
    "short": "Discord Server List Members",
    "desc": "List guild members for inspection, moderation context, or membership lookup.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_list_roles",
    "short": "Discord Server List Roles",
    "desc": "List guild roles with compact permission summaries.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_list_scheduled_events",
    "short": "Discord Server List Scheduled Events",
    "desc": "List scheduled events for the active guild.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_list_threads",
    "short": "Discord Server List Threads",
    "desc": "List active or archived guild threads.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_remove_thread_member",
    "short": "Discord Server Remove Thread Member",
    "desc": "Remove a member from a thread.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_server_update_thread",
    "short": "Discord Server Update Thread",
    "desc": "Rename or change archive or lock settings for a thread.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_voice_get_status",
    "short": "Discord Voice Get Status",
    "desc": "Show the bot voice connection status for this guild.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_voice_join_current_channel",
    "short": "Discord Voice Join Current Channel",
    "desc": "Join the invoker’s current voice channel.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "discord_voice_leave",
    "short": "Discord Voice Leave",
    "desc": "Leave the active guild voice channel.",
    "cat": "discord",
    "color": "#5865F2"
  },
  {
    "name": "image_generate",
    "short": "Image Generate",
    "desc": "Generate an image with Pollinations as a distinct artifact, not a normal text reply.",
    "cat": "gen",
    "color": "#F59E0B"
  },
  {
    "name": "npm_info",
    "short": "npm Package Info",
    "desc": "Lookup npm package metadata including versions, repository, and maintainers.",
    "cat": "dev",
    "color": "#10B981"
  },
  {
    "name": "system_time",
    "short": "System Time",
    "desc": "Calculate timezone offsets for complex scheduling. Current UTC time is already in runtime state, so use this only when explicit offset math is needed.",
    "cat": "system",
    "color": "#6B7280"
  },
  {
    "name": "system_tool_stats",
    "short": "System Tool Stats",
    "desc": "Inspect in-process tool telemetry, cache occupancy, and average latency by tool.",
    "cat": "system",
    "color": "#6B7280"
  },
  {
    "name": "web_read",
    "short": "Web Read",
    "desc": "Fetch and extract the main content from one public URL.",
    "cat": "search",
    "color": "#0EA5E9"
  },
  {
    "name": "web_read_page",
    "short": "Web Read Page",
    "desc": "Read a large page in bounded chunks with continuation fields.",
    "cat": "search",
    "color": "#0EA5E9"
  },
  {
    "name": "web_search",
    "short": "Web Search",
    "desc": "Search the public web and return recent source-grounded results.",
    "cat": "search",
    "color": "#0EA5E9"
  }
];

export const nativeToolCount = nativeTools.length;
