import { writeFile } from 'node:fs/promises';
import path from 'node:path';

import { registerDefaultAgenticTools } from '../src/features/agent-runtime/defaultTools';
import { buildWebsiteNativeTools } from '../src/features/agent-runtime/toolDocs';

export function renderNativeToolsModuleSource(): string {
  const rows = buildWebsiteNativeTools();
  return [
    '// Generated by scripts/generate-native-tools.ts from src/features/agent-runtime/toolDocs.ts.',
    '// Do not edit by hand.',
    `export const nativeTools = ${JSON.stringify(rows, null, 2)};`,
    '',
    'export const nativeToolCount = nativeTools.length;',
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  await registerDefaultAgenticTools();
  const outputPath = path.resolve(__dirname, '../website/src/lib/nativeTools.js');
  await writeFile(outputPath, renderNativeToolsModuleSource(), 'utf8');
  console.log(`Wrote ${outputPath}`);
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`Failed to generate native tools: ${message}`);
  process.exit(1);
});
